### ISSUE TITLE
Getting this error while deploying from heroku button, Help Please

### ISSUE THREAD

**Issue by dfslammirror** [SpEcHlDe/ANYDL-1#2]
2022-01-01T11:06:42.723007+00:00 app[worker.1]: Traceback (most recent call last):
2022-01-01T11:06:42.723484+00:00 app[worker.1]:   File "/app/bot.py", line 39, in <module>
2022-01-01T11:06:42.723737+00:00 app[worker.1]:     app.run()
2022-01-01T11:06:42.723757+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/utilities/run.py", line 61, in run
2022-01-01T11:06:42.723926+00:00 app[worker.1]:     self.start()
2022-01-01T11:06:42.723938+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
2022-01-01T11:06:42.724085+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2022-01-01T11:06:42.724102+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2022-01-01T11:06:42.724401+00:00 app[worker.1]:     return future.result()
2022-01-01T11:06:42.724415+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 68, in start
2022-01-01T11:06:42.724522+00:00 app[worker.1]:     await self.initialize()
2022-01-01T11:06:42.724534+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
2022-01-01T11:06:42.724630+00:00 app[worker.1]:     self.load_plugins()
2022-01-01T11:06:42.724643+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/client.py", line 715, in load_plugins
2022-01-01T11:06:42.724879+00:00 app[worker.1]:     module = import_module(module_path)
2022-01-01T11:06:42.724892+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2022-01-01T11:06:42.725004+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2022-01-01T11:06:42.725016+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-01-01T11:06:42.725106+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-01-01T11:06:42.725159+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2022-01-01T11:06:42.725214+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2022-01-01T11:06:42.725266+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2022-01-01T11:06:42.725352+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2022-01-01T11:06:42.725413+00:00 app[worker.1]:   File "/app/plugins/cb_buttons.py", line 32, in <module>
2022-01-01T11:06:42.725545+00:00 app[worker.1]:     from plugins.dl_button import ddl_call_back
2022-01-01T11:06:42.725559+00:00 app[worker.1]:   File "/app/plugins/dl_button.py", line 28, in <module>
2022-01-01T11:06:42.725669+00:00 app[worker.1]:     from helper_funcs.database import thumb
2022-01-01T11:06:42.725683+00:00 app[worker.1]:   File "/app/helper_funcs/database.py", line 36, in <module>
2022-01-01T11:06:42.725789+00:00 app[worker.1]:     SESSION = start()
2022-01-01T11:06:42.725802+00:00 app[worker.1]:   File "/app/helper_funcs/database.py", line 29, in start
2022-01-01T11:06:42.725902+00:00 app[worker.1]:     engine = create_engine(Config.DB_URI, client_encoding="utf8")
2022-01-01T11:06:42.725916+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
2022-01-01T11:06:42.726178+00:00 app[worker.1]:     return strategy.create(*args, **kwargs)
2022-01-01T11:06:42.726193+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
2022-01-01T11:06:42.726319+00:00 app[worker.1]:     u = url.make_url(name_or_url)
2022-01-01T11:06:42.726333+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
2022-01-01T11:06:42.726488+00:00 app[worker.1]:     return _parse_rfc1738_args(name_or_url)
2022-01-01T11:06:42.726503+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 290, in _parse_rfc1738_args
2022-01-01T11:06:42.726678+00:00 app[worker.1]:     raise exc.ArgumentError(
2022-01-01T11:06:42.726769+00:00 app[worker.1]: sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string ''
2022-01-01T11:06:43.124782+00:00 heroku[worker.1]: Process exited with status 1
2022-01-01T11:06:43.184695+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by SpEcHlDe** [comment]
Try now

If still not work report to https://t.me/+NphHvWpf7Y1mMzM0
